./Game-Boy BROKER CAUGHT_POKEMON 1 OK
./Game-Boy BROKER CAUGHT_POKEMON 1 FAIL

./Game-Boy BROKER NEW_POKEMON Pikachu 2 3 1

./Game-Boy BROKER CATCH_POKEMON Onyx 4 5

./Game-Boy SUSCRIPTOR NEW_POKEMON 10

./Game-Boy BROKER CATCH_POKEMON Charmander 4 5