./Game-Boy BROKER CATCH_POKEMON Pikachu 9 3 #19b
./Game-Boy BROKER CATCH_POKEMON Squirtle 9 3 #20b

./Game-Boy BROKER CAUGHT_POKEMON 10 OK
./Game-Boy BROKER CAUGHT_POKEMON 11 FAIL

./Game-Boy BROKER CATCH_POKEMON Bulbasaur 1 7 #21
./Game-Boy BROKER CATCH_POKEMON Charmander 1 7 #22

./Game-Boy BROKER GET_POKEMON Pichu #9
./Game-Boy BROKER GET_POKEMON Raichu #10