./Game-Boy BROKER CAUGHT_POKEMON 1 OK
./Game-Boy BROKER CAUGHT_POKEMON 1 FAIL

./Game-Boy BROKER CATCH_POKEMON Pikachu 2 3
./Game-Boy BROKER CATCH_POKEMON Squirtle 5 2

./Game-Boy BROKER CATCH_POKEMON Onyx 4 5

./Game-Boy SUSCRIPTOR CAUGHT_POKEMON 10

./Game-Boy BROKER CATCH_POKEMON Charmander 4 5